[[introduction]]
== Introduction to the Spring Security UI Plugin

The Spring Security UI plugin provides CRUD screens and other user management workflows. Non-default functionality is available only if the feature is available; this includes the ACL controllers and views which are enabled if the http://grails.org/plugin/spring-security-acl[ACL plugin] is installed, Requestmaps support which is available if `grails.plugin.springsecurity.securityConfigType` is set to `"Requestmap"` or `SecurityConfigType.Requestmap` in `application.groovy`, and persistent cookies support which is enabled if it has been configured with the `s2-create-persistent-token` script.


=== Installation

Add an entry in the `dependencies` block of your `build.gradle` file, changing the version as needed:

[source,groovy]
[subs="attributes"]
.`build.gradle`
----
dependencies {
   ...
   compile 'org.grails.plugins:spring-security-ui:{projectVersion}'
   ...
----

NOTE: Version 3.1.0 is only compatible with Grails 3.3.x or higher.

For previous Grails 3 versions ( 3.0.x, 3.1.x and 3.2.x ) use:

[source,groovy]
[subs="attributes"]
.`build.gradle`
----
dependencies {
   ...
   compile 'org.grails.plugins:spring-security-ui:3.0.2'
   ...
----

Also be sure to update the versions when new releases are available.

=== Release History

* Sep 26, 2017
** 3.1.0 release
* Jul 28, 2017
** 3.0.2 release
* Jul 27, 2017
** 3.0.1 release
* April 15, 2016
** 3.0.0.M2 release
* December 21, 2015
** 3.0.0.M1 release
* December 21, 2015
** 1.0-RC3 release
* May 20, 2014
** 1.0-RC2 release
* November 11, 2013
** 1.0-RC1 release
** http://jira.grails.org/secure/ReleaseNote.jspa?projectId=10233&amp;version=13069[JIRA Issues]
* February 12, 2012
** 0.2 release
** http://jira.grails.org/secure/ReleaseNote.jspa?projectId=10233&amp;version=12709[JIRA Issues]
* September 14, 2010
** 0.1.2 release
** http://jira.grails.org/secure/ReleaseNote.jspa?projectId=10233&amp;version=11921[JIRA Issues]
* July 27, 2010
** 0.1.1 release
* July 26, 2010
** initial 0.1 release
